name: Bug report
description: Create a Cromite bug report
body:
  - type: markdown
    attributes:
      value: |
        Welcome! Thanks for taking the time to submit a bug report.

        If this is not a bug about the Cromite browser, or you are looking for a place to ask a question to the community,
        then please use the [GitHub Discussions](https://github.com/uazo/cromite/discussions) instead.

        Make sure you have acknowledged and completed this template before submitting your issue.

        Please read it carefully: incorrect issues will be automatically closed and ignored.

  - type: checkboxes
    id: preliminary_checklist
    attributes:
      label: Preliminary checklist
      options:
        - label: "I have read the [README](https://github.com/uazo/cromite/blob/master/README.md)."
          required: true
        - label: "I have searched the existing issues for my problem. This is a new ticket, NOT a duplicate or related to another open issue."
          required: true
        - label: "I have updated Cromite to the latest version. The bug is reproducible on this latest version."
          required: true
        - label: "This is a bug report about the Cromite browser; not the website nor F-Droid nor anything else."
          required: true

  - type: dropdown
    id: is_chromium
    attributes:
      label: Can the bug be reproduced with corresponding Chromium version?
      description: |
          Please pick the same version of Chromium as Cromite
          If the bug is reproducible then it might be a configuration issue or an upstream bug. Upstream bugs can be reported on the [Chromium issue tracker](https://bugs.chromium.org/p/chromium/issues/list) and
          do not forget to read [Chromium project bug reporting guidelines](https://www.chromium.org/for-testers/bug-reporting-guidelines) first.

          If the bug is related to functionality that does not exist in Chromium then answer "No".
      multiple: false
      options:
        - "Yes"
        - "No"
    validations:
      required: true

  - type: dropdown
    id: is_chromium2
    attributes:
      label: Are you sure?
      description: |
          Please check your answer above again, it is important information

          If the bug is related to functionality that does not exist in Chromium then answer "No".
      multiple: false
      options:
        - "Yes"
        - "No"
    validations:
      required: true
      
  - type: input
    id: cromite_version
    attributes:
      label: Cromite version
      description: What version of Cromite are you using? Please specify a single version e.g. `96.0.4664.1` not `latest`. If this is not the latest version then please update and retry before submitting this bug report.
    validations:
      required: true

  - type: dropdown
    id: device_architecture
    attributes:
      label: Device architecture
      multiple: false
      options:
        - arm
        - arm64
        - arm64-v8a
        - armeabi-v7a
        - x86
        - x64
        - windows
        - all
    validations:
      required: true

  - type: dropdown
    id: platform_version
    attributes:
      label: Platform version
      multiple: false
      description: What version of Android are you running?
      options:
        - Android 15
        - Android 14
        - Android 13
        - Android 12.1
        - Android 12
        - Android 11
        - Android 10
        - Android 9
        - Android 8.1
        - Android 8.0
        - Android 7.1
        - Android 7.0
        - Android Emulator
        - Windows 10
        - Windows 11
        - I prefer not to write it/No matter
    validations:
      required: true

  - type: input
    id: device_model
    attributes:
      label: Android Device model
      description: What is your device model? This can usually be found in your device's settings in the "About" section.
      placeholder: (e.g. `OnePlus 8 (IN2010)`, or `SM-G960UZKABST`, etc.)
    validations:
      required: true

  - type: dropdown
    id: is_android_rooted
    attributes:
      label: Is the device rooted?
      description: |
          The information is important but not essential; it allows additional checks to be made.
      multiple: false
      options:
        - "Yes"
        - "No"
        - "I prefer not to write it"
    validations:
      required: true
      
  - type: textarea
    id: changed_flags
    attributes:
      label: Changed flags
      description: |
        These are the flags changed under `chrome://flags`.
        Report all the flags with non-default configuration (they will be blue-highlighted).

        If no flags are changed then write 'no flags changed'.
      placeholder: show-overdraw-feedback, enable-parallel-downloading
    validations:
      required: true

  - type: dropdown
    id: is_incognito
    attributes:
      label: Is this bug happening ONLY in an incognito tab?
      multiple: false
      options:
        - "Yes"
        - "No"
        - "Always Incognito Mode"
    validations:
      required: true

  - type: dropdown
    id: adblock
    attributes:
      label: Is this bug caused by the adblocker?
      description: You can test this by temporarily allowing ads for the site.
      multiple: false
      options:
        - "Yes"
        - "No"
    validations:
      required: true

  - type: textarea
    id: bug_crash
    attributes:
      label: Is this bug a crash?
      description: |
        1. No.
        2. Yes, I have attached the crash report dump that I downloaded from `chrome://crashes`
        3. Yes, I have copy/pasted the crash dump
      placeholder: |
        Drag the crash report dump here to attach it or paste the logcat dump individuated with `adb logcat | grep -E '( cr_|cromite|chromium)'`.
    validations:
      required: true

  - type: textarea
    id: bug_description
    attributes:
      label: Describe the bug
      description: Write a clear and concise description of the bug.
    validations:
      required: true

  - type: textarea
    id: bug_steps
    attributes:
      label: Steps to reproduce the bug
      description: |
        Explain how to cause the bug as clearly as possible. Bugs that are not reproducible cannot be investigated.

        Also, do not write "any website": please specify which URLs can be used to reproduce the issue.
      placeholder: |
        Steps to reproduce the bug (e.g.):
        1. Go to '...'
        2. Click on '...'
        3. Scroll down to '...'
        4. See error
    validations:
      required: true

  - type: textarea
    id: expected_behavior
    attributes:
      label: Expected behavior
      description: A clear and concise description of what you expected to happen.
    validations:
      required: true

  - type: textarea
    id: screenshots
    attributes:
      label: Screenshots
      description: |
        If applicable, add screenshots to help explain your problem.
        Otherwise, ignore this section.
      placeholder: |
        Drag the screenshot files here to attach them.
    validations:
      required: false
