name: Feature request
description: Create a Cromite feature request
body:
  - type: markdown
    attributes:
      value: |
        Welcome! Thanks for taking time to submit a feature request.

        If this is not a feature request about the Cromite browser, or you are looking for a place
        to ask a question to the community then please use the [GitHub Discussions](https://github.com/uazo/cromite/discussions) instead.

        Make sure you have acknowledged and completed this template before submitting your issue.

        Please read it carefully: incorrect issues will be automatically closed and ignored.

        Note:
          - Features unrelated to privacy will not be considered.
          - Do not ask "I would like feature X which is available in browser Y."

  - type: checkboxes
    id: preliminary_checklist
    attributes:
      label: Preliminary checklist
      options:
        - label: "I have read the [README](https://github.com/uazo/cromite/blob/master/README.md)"
          required: true
        - label: "I have searched [existing issues](https://github.com/uazo/cromite/issues) for my feature request. This is a new issue (NOT a duplicate) and is not related to another issue."
          required: true
        - label: "I have searched [wont fix issues](https://github.com/uazo/cromite/issues?q=label%3Awontfix) and this request is not among them"
          required: true
        - label: "This is a feature request for the Cromite browser; not the website nor F-Droid nor anything else."
          required: true

  - type: dropdown
    id: is_privacy_related
    attributes:
      label: Is your feature request related to privacy?
      description: Features that are not related to privacy are not considered.
      multiple: false
      options:
        - "<please select>"
        - "Yes"
        - "No"
    validations:
      required: true

  - type: textarea
    id: is_patch_available
    attributes:
      label: Is there a patch available for this feature somewhere?
      description: If yes please provide URL and related license information.
    validations:
      required: true

  - type: textarea
    id: solution_description
    attributes:
      label: Describe the solution you would like
      description: A clear and concise description of what you want to happen.
    validations:
      required: true

  - type: textarea
    id: alternatives_considered
    attributes:
      label: Describe alternatives you have considered
      description: A clear and concise description of any alternative solutions or features you have considered.
    validations:
      required: true
