name: Build Sysbox
permissions:
  contents: write
      
on:
  workflow_dispatch:
    inputs:
      sha:
        description: 'Sysbox SHA'
        required: true
        default: ''
        
env:
  SYSBOX_SHA: ${{ github.event.inputs.sha }}
  
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v2
        with:
          path: cromite
          fetch-depth: 1

      - name: Build patched sysbox
        run: |
          git clone --recursive https://github.com/nestybox/sysbox.git
          cd sysbox
          git checkout $SYSBOX_SHA
          git submodule update --recursive

          cd sysbox-runc/
          git apply --ignore-whitespace ../../cromite/tools/images/sysbox/add-x86-x32-arch.patch
          git status
          cd ..

          make sysbox-static TARGET_ARCH=x64

          zip -r build.zip build

      - name: Publish
        uses: actions/upload-artifact@v2
        with:
          name: build.zip
          path: sysbox/build.zip
